### ISSUE TITLE
[BUG] Not working with Velocity CTD

### ISSUE THREAD

**Issue by whiler-sesame** [Elytrium/LimboAPI#163]
Velocity CTD changed packet registration system in https://github.com/GemstoneGG/Velocity-CTD/commit/a93bdbb482f52365252e04be4b146c1c8d2b4542, so now LimboAPI won't start. I'm not sure whether this should be fixed on your end or on their end.

**Comment by hevav** [comment]
This fork changed too many things in the package registry code. And it is quite possible that this fork developer could change some internal stuff again. It will be impossible for us to support "independent forks" because they might change too many internal things.

I don't see any benefits of the changes in this commit. I think it's better for the fork developer to rollback these changes, so that the fork supports more plugins.

**Comment by R00tB33rMan** [comment]
> This fork changed too many things in the package registry code. And it is quite possible that this fork developer could change some internal stuff again. It will be impossible for us to support "independent forks" because they might change too many internal things.
> 
> I don't see any benefits of the changes in this commit. I think it's better for the fork developer to rollback these changes, so that the fork supports more plugins.

Breakage is in conjunction with this impending PR that has already and safely been merged. I'd suspect that you'd all need to make changes to LimboAPI once this PR is merged: https://github.com/PaperMC/Velocity/pull/1314
