### ISSUE TITLE
[Feature] Standalone version!

### ISSUE THREAD

**Issue by zReport02** [Elytrium/LimboAPI#34]
Hi, I've tried using this plugin on my server and it's very nice and works fine!

But I would like to detach it from the proxy as I think it can weigh it down with a large amount of player and using it as an authlobby, sorting system and more!

So I would like to ask if it is possible to have the standalone version

**Comment by hevav** [comment]
This plugin is really lightweight, it can handle thousands of players without high resource consumption, since most of the network packets are prepared: they are stored as a ready-to-send Netty's ByteBuf.
As for "standalone" version, we don't want to do it, Velocity+Plugin is more optimized way to make Limbos.
